/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited.
// It is normally regenerated by Next.js; committed here so `tsc` works before
// the first `next dev`/`next build`.
