"""phase1 initial schema

Revision ID: eae308c75ce3
Revises: 
Create Date: 2026-09-13 15:11:56.501999
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = 'eae308c75ce3'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # pgvector must exist before the embeddings table's `vector` column is created.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('agent_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('trigger', sa.String(length=64), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed', 'cancelled')", name='ck_agent_runs_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_runs_status', 'agent_runs', ['status'], unique=False)
    op.create_table('embeddings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=32), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=True),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('embedding', Vector(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_type', 'owner_id', 'model', name='uq_embeddings_owner_model')
    )
    op.create_index('ix_embeddings_owner', 'embeddings', ['owner_type', 'owner_id'], unique=False)
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_entities_canonical_name', 'entities', ['canonical_name'], unique=False)
    op.create_index('ix_entities_entity_type', 'entities', ['entity_type'], unique=False)
    op.create_index('ix_entities_status', 'entities', ['status'], unique=False)
    op.create_table('graph_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_type', sa.String(length=16), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_type', sa.String(length=16), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.String(length=64), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_count', sa.Integer(), nullable=False),
    sa.Column('first_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_observed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source_node_type IN ('concept', 'entity')", name='ck_graph_edges_source_node_type'),
    sa.CheckConstraint("target_node_type IN ('concept', 'entity')", name='ck_graph_edges_target_node_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_node_type', 'source_node_id', 'target_node_type', 'target_node_id', 'relationship_type', name='uq_graph_edges_edge')
    )
    op.create_index('ix_graph_edges_relationship_type', 'graph_edges', ['relationship_type'], unique=False)
    op.create_index('ix_graph_edges_source', 'graph_edges', ['source_node_type', 'source_node_id'], unique=False)
    op.create_index('ix_graph_edges_target', 'graph_edges', ['target_node_type', 'target_node_id'], unique=False)
    op.create_table('sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_key')
    )
    op.create_table('time_series_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_type', sa.String(length=16), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('granularity', sa.String(length=16), nullable=False),
    sa.Column('bucket_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('mention_count', sa.Integer(), nullable=False),
    sa.Column('unique_authors', sa.Integer(), nullable=False),
    sa.Column('engagement_sum', sa.Float(), nullable=False),
    sa.Column('source_diversity', sa.Integer(), nullable=False),
    sa.Column('metrics', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("granularity IN ('hour', 'day', 'week', 'month')", name='ck_tso_granularity'),
    sa.CheckConstraint("subject_type IN ('concept', 'entity', 'edge')", name='ck_tso_subject_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_type', 'subject_id', 'granularity', 'bucket_start', name='uq_tso_bucket')
    )
    op.create_index('ix_tso_subject', 'time_series_observations', ['subject_type', 'subject_id', 'bucket_start'], unique=False)
    op.create_table('agent_hypotheses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('supporting_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('contradicting_evidence', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_hypotheses_run_id', 'agent_hypotheses', ['run_id'], unique=False)
    op.create_table('agent_observations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('observation_type', sa.String(length=64), nullable=True),
    sa.Column('subject_type', sa.String(length=16), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_observations_run_id', 'agent_observations', ['run_id'], unique=False)
    op.create_table('agent_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('concept_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('entity_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('prediction_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_reports_run_id', 'agent_reports', ['run_id'], unique=False)
    op.create_table('authors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_author_id', sa.String(length=256), nullable=False),
    sa.Column('username', sa.String(length=256), nullable=True),
    sa.Column('display_name', sa.String(length=256), nullable=True),
    sa.Column('profile_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_author_id', name='uq_authors_source_external')
    )
    op.create_index('ix_authors_source_id', 'authors', ['source_id'], unique=False)
    op.create_index('ix_authors_username', 'authors', ['username'], unique=False)
    op.create_table('seeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('seed_type', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('canonical_value', sa.String(length=512), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('source_config_version', sa.Integer(), nullable=True),
    sa.Column('imported_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_seeds_enabled', 'seeds', ['enabled'], unique=False)
    op.create_index('ix_seeds_seed_type', 'seeds', ['seed_type'], unique=False)
    op.create_index('ix_seeds_source_id', 'seeds', ['source_id'], unique=False)
    op.create_table('agent_predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('hypothesis_id', sa.UUID(), nullable=True),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('horizon', sa.String(length=64), nullable=True),
    sa.Column('evaluation_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('actual_outcome', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evaluation_metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'correct', 'incorrect', 'partial', 'unresolved')", name='ck_agent_predictions_status'),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['agent_hypotheses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_agent_predictions_evaluation_at', 'agent_predictions', ['evaluation_at'], unique=False)
    op.create_index('ix_agent_predictions_run_id', 'agent_predictions', ['run_id'], unique=False)
    op.create_index('ix_agent_predictions_status', 'agent_predictions', ['status'], unique=False)
    op.create_table('concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.String(length=200), nullable=True),
    sa.Column('canonical_name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('concept_type', sa.String(length=64), nullable=True),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('seed_id', sa.UUID(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['seed_id'], ['seeds.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_concepts_canonical_name', 'concepts', ['canonical_name'], unique=False)
    op.create_index('ix_concepts_concept_type', 'concepts', ['concept_type'], unique=False)
    op.create_index('ix_concepts_seed_id', 'concepts', ['seed_id'], unique=False)
    op.create_index('ix_concepts_status', 'concepts', ['status'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('external_id', sa.String(length=512), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('engagement', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('raw_payload_uri', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_posts_source_external')
    )
    op.create_index('ix_posts_author_id', 'posts', ['author_id'], unique=False)
    op.create_index('ix_posts_collected_at', 'posts', ['collected_at'], unique=False)
    op.create_index('ix_posts_content_hash', 'posts', ['content_hash'], unique=False)
    op.create_index('ix_posts_published_at', 'posts', ['published_at'], unique=False)
    op.create_table('post_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('concept_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('extraction_model', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concepts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'concept_id', 'extraction_method', name='uq_post_concepts_assoc')
    )
    op.create_index('ix_post_concepts_concept_id', 'post_concepts', ['concept_id'], unique=False)
    op.create_index('ix_post_concepts_post_id', 'post_concepts', ['post_id'], unique=False)
    op.create_table('post_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('extraction_method', sa.String(length=64), nullable=False),
    sa.Column('extraction_model', sa.String(length=128), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'entity_id', 'extraction_method', name='uq_post_entities_assoc')
    )
    op.create_index('ix_post_entities_entity_id', 'post_entities', ['entity_id'], unique=False)
    op.create_index('ix_post_entities_post_id', 'post_entities', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_entities_post_id', table_name='post_entities')
    op.drop_index('ix_post_entities_entity_id', table_name='post_entities')
    op.drop_table('post_entities')
    op.drop_index('ix_post_concepts_post_id', table_name='post_concepts')
    op.drop_index('ix_post_concepts_concept_id', table_name='post_concepts')
    op.drop_table('post_concepts')
    op.drop_index('ix_posts_published_at', table_name='posts')
    op.drop_index('ix_posts_content_hash', table_name='posts')
    op.drop_index('ix_posts_collected_at', table_name='posts')
    op.drop_index('ix_posts_author_id', table_name='posts')
    op.drop_table('posts')
    op.drop_index('ix_concepts_status', table_name='concepts')
    op.drop_index('ix_concepts_seed_id', table_name='concepts')
    op.drop_index('ix_concepts_concept_type', table_name='concepts')
    op.drop_index('ix_concepts_canonical_name', table_name='concepts')
    op.drop_table('concepts')
    op.drop_index('ix_agent_predictions_status', table_name='agent_predictions')
    op.drop_index('ix_agent_predictions_run_id', table_name='agent_predictions')
    op.drop_index('ix_agent_predictions_evaluation_at', table_name='agent_predictions')
    op.drop_table('agent_predictions')
    op.drop_index('ix_seeds_source_id', table_name='seeds')
    op.drop_index('ix_seeds_seed_type', table_name='seeds')
    op.drop_index('ix_seeds_enabled', table_name='seeds')
    op.drop_table('seeds')
    op.drop_index('ix_authors_username', table_name='authors')
    op.drop_index('ix_authors_source_id', table_name='authors')
    op.drop_table('authors')
    op.drop_index('ix_agent_reports_run_id', table_name='agent_reports')
    op.drop_table('agent_reports')
    op.drop_index('ix_agent_observations_run_id', table_name='agent_observations')
    op.drop_table('agent_observations')
    op.drop_index('ix_agent_hypotheses_run_id', table_name='agent_hypotheses')
    op.drop_table('agent_hypotheses')
    op.drop_index('ix_tso_subject', table_name='time_series_observations')
    op.drop_table('time_series_observations')
    op.drop_table('sources')
    op.drop_index('ix_graph_edges_target', table_name='graph_edges')
    op.drop_index('ix_graph_edges_source', table_name='graph_edges')
    op.drop_index('ix_graph_edges_relationship_type', table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index('ix_entities_status', table_name='entities')
    op.drop_index('ix_entities_entity_type', table_name='entities')
    op.drop_index('ix_entities_canonical_name', table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_embeddings_owner', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index('ix_agent_runs_status', table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
